---
- name: Installing NFS Server
  hosts: nfs_server
  become: true

  vars:
    mountable_share_drive: '/dev/sda1'
    nfsexport: /share
    src_exports: ~/templates/exports.j2
    #nfsserver: hostvars[inventory_hostname]['facter_ipaddress_eth1'] #192.168.99.150

  tasks:
    - name: update the apt cache
      apt:
        update_cache: yes

    - name: Create mountable dir
      file: path={{ nfsexport }} state=directory mode=777 owner=root group=root
      tags: nfs_server

    - name: Ensure NFS utilities are installed.
      apt:
        name: ['nfs-common','nfs-kernel-server']
        state: present
        update_cache: yes
      tags: nfs_server

    - name: copy /etc/exports
      template: src={{ src_exports }} dest=/etc/exports owner=root group=root
      tags: nfs_server

    - name: restart nfs server
      service: name=nfs-kernel-server state=restarted
      tags: nfs_server